### ISSUE TITLE
com.ciscowebex:androidsdk:2.5.0 - Video calling blank screen remote view

### ISSUE THREAD

**Issue by TRACKtechLLC** [webex/webex-android-sdk#27]
2.5.0 version of the SDK does not display remote video in the remote view media view renderer layout when calling from the integration widget. To duplicate this issue, supply an access token and use a personId or email here https://code.s4d.io/widget-demo/production/index.html and call a very basic implementation of the SDK and remote view shows a black screen.

Whereas when downgrading to 2.2.0 it shows the remote video in the Android test app as expected. 

We are looking to use the new messaging features in 2.5.0 and are running into the video issue.

**Comment by fadante** [comment]
Message list is a known issue and has been fixed in the last snapshot version 2.5.0.19. So, update and retry:

For that, you have to apply the following patch:
```
maven {
    url 'https://devhub.cisco.com/artifactory/webexsdk-SNAPSHOT/'
}
implementation('com.ciscowebex:androidsdk:2.5.0.9-SNAPSHOT@aar', {
    transitive = true
    changing = true
}
```
And also, the snapshot repo should be added in Webex-Android-SDK-example/build.gradle file to apply the patch:
```
maven {
            url 'https://devhub.cisco.com/artifactory/webexsdk-SNAPSHOT/'
        }
```
Note that you should delete your ~/.gradle/cache prior to rebuilding the app.
