### ISSUE TITLE
Support for Android < 27

### ISSUE THREAD

**Issue by terencemackie** [webex/webex-android-sdk#5]
Hi,

Although the readme states support for API >= 21, it appears to be restricted to 27.

When I add the Webex Android SDK to a project (as per the readme instructions) and target an Android sdk of version 23, I receive the following error:
Invoke-customs are only supported starting with Android O (--min-api 26)

This error occurs just with the addition of the Webex Android SDK dependency, without any other code.

For the project I am trying to add webex support to, I have a restriction on Android 23.

Can you help?

Thanks,

Terence Mackie

**Comment by olivierproffit** [comment]
@terencemackie by any chance, have you already reached to our developer support https://github.com/webex/webex-android-sdk ?

**Comment by mrjaimisra** [comment]
@terencemackie the link to support is https://developer.webex.com/support

**Comment by terencemackie** [comment]
Hi @olivierproffit yes, I contacted webex developer support. The only response I got was "it should work". I did speak to one of the business reps who did provide some help, and ended up recommending that we do not use the sdk but the webex android application instead.

The end result is that the webex andoird sdk does not support <26. An update to the readme might be in order. :)

It's a shame, because embedding the webex interface within an application can result in a much smoother experience for the user.

**Comment by olivierproffit** [comment]
Hi @terencemackie  sorry to hear that you didn't get the answer we were waiting for. Usually chatting with the dev support in the space #webex4devs is very effective. But for more follow-up or deeper troubleshooting, you can also open a ticket by sending your issue details by email to devsupport@webex.com.
On your specific issue, we've seen it in the past due to missing configuration in the app's build script. Our prerequisites are right.
Depending on the error message, you may need to include the following in the app's gradle script.
This is often because the app uses lambda or something else. it’s usually not related to SDK version or api level.
`android { 
compileOptions { 
sourceCompatibility JavaVersion.VERSION_1_8 
targetCompatibility JavaVersion.VERSION_1_8 
} 
}`
Please let us know if it solves your issue.

**Comment by olivierproffit** [comment]
@terencemackie  checking if it's solved for you ?

**Comment by terencemackie** [comment]
Hi @olivierproffit , this didn't solve the problem. I was discussing this issue with one of the Webex reps, but the end result was to switch to Android >= 26 (or not use webex). I am no longer working on the application, so I can't provide more details than what I have already (or by trying the demo application).

Kind regards,

Terence

**Comment by olivierproffit** [comment]
Ok, closing this issue since you don't work on it anymore but let me know if we need to investigate more.

**Comment by olivierproffit** [comment]
Ok, closing this issue since you don't work on it anymore but let me know if we need to investigate more.
